name: Auto assign to Software Task Project

on:
    issues:
        types: [ opened ]
    pull_request:
        types: [ opened ]

jobs:
    assign_to_project:
        name: Add issues and PRs to Project
        runs-on: ubuntu-latest
        steps:
            - name: Assign to Project
              uses: actions/add-to-project@v1.0.2
              with:
                project-url: https://github.com/orgs/UMSATS/projects/12
                github-token: ${{ secrets.ADD_TO_PROJECT_TOKEN }}
