[project]
name = "umsats-soti"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyserial>=3.5",
    "serial>=0.0.97",
    "urwid>=3.0.3",
    "numpy>=2.1.1"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
soti = "umsats_soti.__main__:main"
